# This file was generated by GoReleaser. DO NOT EDIT.
cask "cft" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "03569244782333a47180ab39d5159e0eab6bea61b4361483c0304c9d7546ae47"
      url "https://github.com/Okabe-Junya/cft/releases/download/v#{version}/cft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea0a0fdf49bf9bdd733baca1901054456c1f4248c4b1a162a2141cbfe667f0e6"
      url "https://github.com/Okabe-Junya/cft/releases/download/v#{version}/cft_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cft"
  desc "macOS-only CLI for managing least-privilege Cloudflare API tokens declaratively."
  homepage "https://github.com/Okabe-Junya/cft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cft"
  bash_completion "completions/cft.bash"
  fish_completion "completions/cft.fish"
  zsh_completion "completions/cft.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cft"]
    end
  end

  # No zap stanza required

end
