# This file was generated by GoReleaser. DO NOT EDIT.
cask "cft" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "e78550710f004c60b3279956f11810b0a1d3f3c9d4cc8e74b3e9bde828bcdeb1"
      url "https://github.com/Okabe-Junya/cft/releases/download/v#{version}/cft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7405070a39c0b7deee9cebfc90e2ebc6b7f02993ede9f7533f26d7ec2fa2120c"
      url "https://github.com/Okabe-Junya/cft/releases/download/v#{version}/cft_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cft"
  desc "macOS-only CLI for managing least-privilege Cloudflare API tokens declaratively."
  homepage "https://github.com/Okabe-Junya/cft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cft"
  bash_completion "completions/cft.bash"
  fish_completion "completions/cft.fish"
  zsh_completion "completions/cft.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cft"]
    end
  end

  # No zap stanza required

end
