# This file was generated by GoReleaser. DO NOT EDIT.
cask "cft" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5a29aa4b2e8fb75cb385a0e542a689399f7e256ed61b379fbb4bbcb9793c12d5"
      url "https://github.com/Okabe-Junya/cft/releases/download/v#{version}/cft_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce0551d37fd68b11238c620f90a10ef9c86b4b1804d6d956fce23e189c41aace"
      url "https://github.com/Okabe-Junya/cft/releases/download/v#{version}/cft_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cft"
  desc "macOS-only CLI for managing least-privilege Cloudflare API tokens declaratively."
  homepage "https://github.com/Okabe-Junya/cft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cft"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cft"]
    end
  end

  # No zap stanza required

end
