# typed: false
# frozen_string_literal: true

# This file is generated by Okabe-Junya/autocomplete's release workflow. DO NOT EDIT.
class AutocompleteSpecs < Formula
  desc "Prebuilt completion specs for Kiro CLI autocomplete"
  homepage "https://github.com/Okabe-Junya/autocomplete"
  url "https://github.com/Okabe-Junya/autocomplete/releases/download/v2.693.0/autocomplete-specs-2.693.0.tar.gz"
  sha256 "e5a8ba79fdcee41a84a9ecd06f18a2763a41ff2533652063523588fd1a319027"
  version "2.693.0"
  license "MIT"

  def install
    # The tarball's single top-level "build/" directory is stripped by
    # Homebrew's staging, so the specs land directly in the buildpath.
    (pkgshare/"build").install Dir["*"]
  end

  def caveats
    # post_install cannot create this symlink: Homebrew sandboxes it with a
    # redirected HOME, so writes to "~" silently land in a throwaway dir.
    <<~EOS
      To let Kiro CLI load these specs, create a one-time symlink
      (move any existing real directory aside first):
        mkdir -p ~/.fig/autocomplete
        ln -sfn #{opt_pkgshare}/build ~/.fig/autocomplete/build
      The link target is stable, so future \`brew upgrade\`s apply automatically.
    EOS
  end

  test do
    assert_path_exists pkgshare/"build/kubectl.js"
  end
end
