# typed: false
# frozen_string_literal: true

# This file is generated by Okabe-Junya/autocomplete's release workflow. DO NOT EDIT.
class AutocompleteSpecs < Formula
  desc "Prebuilt completion specs for Kiro CLI autocomplete"
  homepage "https://github.com/Okabe-Junya/autocomplete"
  url "https://github.com/Okabe-Junya/autocomplete/releases/download/v2026.07.04.2008/autocomplete-specs-2026.07.04.2008.tar.gz"
  sha256 "848fc73e49c26d29a7dca7981389c872d2299b5007572392d3796d750524b082"
  version "2026.07.04.2008"
  license "MIT"

  def install
    # The tarball's single top-level "build/" directory is stripped by
    # Homebrew's staging, so the specs land directly in the buildpath.
    (pkgshare/"build").install Dir["*"]
  end

  def caveats
    # post_install cannot create this symlink: Homebrew sandboxes it with a
    # redirected HOME, so writes to "~" silently land in a throwaway dir.
    <<~EOS
      To let Kiro CLI load these specs, create a one-time symlink
      (move any existing real directory aside first):
        mkdir -p ~/.fig/autocomplete
        ln -sfn #{opt_pkgshare}/build ~/.fig/autocomplete/build
      The link target is stable, so future \`brew upgrade\`s apply automatically.
    EOS
  end

  test do
    assert_path_exists pkgshare/"build/kubectl.js"
  end
end
