# typed: false
# frozen_string_literal: true

# This file is generated by Okabe-Junya/autocomplete's release workflow. DO NOT EDIT.
class AutocompleteSpecs < Formula
  desc "Prebuilt completion specs for Kiro CLI autocomplete"
  homepage "https://github.com/Okabe-Junya/autocomplete"
  url "https://github.com/Okabe-Junya/autocomplete/releases/download/v0.1.0/autocomplete-specs-0.1.0.tar.gz"
  sha256 "1bf9d35c14bdfbeb9871825dec124700a3965ee7c04b9e7cde445efbceb34b49"
  version "0.1.0"
  license "MIT"

  def install
    # The tarball's single top-level "build/" directory is stripped by
    # Homebrew's staging, so the specs land directly in the buildpath.
    (pkgshare/"build").install Dir["*"]
  end

  def caveats
    <<~EOS
      To let Kiro CLI load these specs, create a one-time symlink:
        mkdir -p ~/.fig/autocomplete
        ln -sfn #{opt_pkgshare}/build ~/.fig/autocomplete/build
      Future upgrades apply automatically.
    EOS
  end

  test do
    assert_path_exists pkgshare/"build/kubectl.js"
  end
end
