# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcloudctx < Formula
  desc "Fast way to switch between gcloud configurations, inspired by kubectx"
  homepage "https://github.com/Okabe-Junya/gcloudctx"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Okabe-Junya/gcloudctx/releases/download/v0.1.0/gcloudctx_0.1.0_darwin_amd64.tar.gz"
      sha256 "911335c4f958110ae0222a7ccb275abee6c5ac6ba788e617b1f69eafbe3fe80f"

      def install
        bin.install "gcloudctx"
        generate_completions_from_executable(bin/"gcloudctx", "completion", base_name: "gcloudctx")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Okabe-Junya/gcloudctx/releases/download/v0.1.0/gcloudctx_0.1.0_darwin_arm64.tar.gz"
      sha256 "8122d4d51d48b5c3c1895d1aa81c55623b2ef3c7355d48c5228a023b3cbc3afb"

      def install
        bin.install "gcloudctx"
        generate_completions_from_executable(bin/"gcloudctx", "completion", base_name: "gcloudctx")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Okabe-Junya/gcloudctx/releases/download/v0.1.0/gcloudctx_0.1.0_linux_amd64.tar.gz"
      sha256 "c677345281b65296ccd69a3b8b2f123a348dab78521368d0511005700ae63cd4"
      def install
        bin.install "gcloudctx"
        generate_completions_from_executable(bin/"gcloudctx", "completion", base_name: "gcloudctx")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Okabe-Junya/gcloudctx/releases/download/v0.1.0/gcloudctx_0.1.0_linux_arm64.tar.gz"
      sha256 "258b799396926056dc48ae58126bb348565dc2828f8911d10082e876f9ec891b"
      def install
        bin.install "gcloudctx"
        generate_completions_from_executable(bin/"gcloudctx", "completion", base_name: "gcloudctx")
      end
    end
  end

  test do
    system "#{bin}/gcloudctx", "--version"
  end
end
