# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nigiri < Formula
  desc "nigiri - A Git branch management tool"
  homepage "https://github.com/oota-sushikuitee/nigiri"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.1.3/nigiri_0.1.3_darwin_amd64.tar.gz"
      sha256 "d97a012e1fd586edf861660cef49df45fce763f3eaabbde0c99b76ac88fb8a05"

      def install
        bin.install "nigiri"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.1.3/nigiri_0.1.3_darwin_arm64.tar.gz"
      sha256 "249b049933d712af43f1c7fcebbc3a0412cec639eedd489797d230f60981d46b"

      def install
        bin.install "nigiri"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.1.3/nigiri_0.1.3_linux_amd64.tar.gz"
      sha256 "18164c7ae4b0268bbb241f3892b57bc65ab439fb36e681bd16a8f63c4dd2760f"
      def install
        bin.install "nigiri"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.1.3/nigiri_0.1.3_linux_arm64.tar.gz"
      sha256 "59acde3c831c7ef149c657dd8d4d69e1cb49c6c3c99b3273e9d17eeef1b76259"
      def install
        bin.install "nigiri"
      end
    end
  end

  test do
    system "#{bin}/nigiri", "--version"
  end
end
