# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nigiri < Formula
  desc "Manage upstream VCS repositories and build artifacts across versions"
  homepage "https://github.com/oota-sushikuitee/nigiri"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.2.1/nigiri_0.2.1_darwin_amd64.tar.gz"
      sha256 "a525b4cbdaf562075617701dfb55a567a90bd0832c6622f1aaf22b205a4cabc7"

      define_method(:install) do
        bin.install "nigiri"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.2.1/nigiri_0.2.1_darwin_arm64.tar.gz"
      sha256 "a9bafec69dc4403ac7b219989b61988975413533ea1f6b797cc96fed55a9e83d"

      define_method(:install) do
        bin.install "nigiri"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.2.1/nigiri_0.2.1_linux_amd64.tar.gz"
      sha256 "212bdf515b0d2e7576deb9de0fff7f2d1d963785181aa31607d60a51eb6d974c"
      define_method(:install) do
        bin.install "nigiri"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oota-sushikuitee/nigiri/releases/download/v0.2.1/nigiri_0.2.1_linux_arm64.tar.gz"
      sha256 "01dda269f6daa0334d2fc09bf63e0041f0ff761933343f54651e929a4bca43f7"
      define_method(:install) do
        bin.install "nigiri"
      end
    end
  end

  test do
    system "#{bin}/nigiri", "--version"
  end
end
